# Generated by Django 6.0.3 on 2026-03-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('date', 'description'), name='unique_holiday_date_description'),
        ),
    ]
