# Generated by Django 6.0.3 on 2026-03-14 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_league_wide_logo_url'),
        ('scheduling', '0002_holiday_unique_holiday_date_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('working', 'Working'), ('active', 'Active')], max_length=20)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.league')),
            ],
            options={
                'ordering': ['league__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('league', 'name'), name='unique_season_name_per_league'), models.UniqueConstraint(condition=models.Q(('status', 'working')), fields=('league',), name='unique_working_season_per_league'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('league',), name='unique_active_season_per_league')],
            },
        ),
    ]
