# Generated by Django 6.0.3 on 2026-03-14 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='scheduling.season')),
            ],
            options={
                'ordering': ['season', 'date'],
                'constraints': [models.UniqueConstraint(fields=('season', 'date'), name='unique_week_date_per_season'), models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('season', 'number'), name='unique_week_number_per_season')],
            },
        ),
    ]
