# Generated by Django 6.0.3 on 2026-03-14 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_league_wide_logo_url'),
        ('scheduling', '0004_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='scheduling.week')),
            ],
            options={
                'ordering': ['week', 'home_team__name', 'away_team__name'],
            },
        ),
    ]
