# Generated by Django 6.0.3 on 2026-03-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['week', 'sort_order', 'home_team__name', 'away_team__name']},
        ),
        migrations.AddField(
            model_name='match',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
