# Generated by Django 6.0.3 on 2026-03-18 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_team_team_rank'),
        ('scheduling', '0006_alter_match_options_match_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_seasons', to='core.league')),
            ],
            options={
                'ordering': ['-archived_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('team_name', models.CharField(blank=True, max_length=255)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('games_lost', models.PositiveIntegerField(default=0)),
                ('run_outs', models.PositiveIntegerField(default=0)),
                ('eight_on_the_breaks', models.PositiveIntegerField(default=0)),
                ('sweeps', models.PositiveIntegerField(default=0)),
                ('archived_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='scheduling.archivedseason')),
            ],
            options={
                'ordering': ['player_name'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('matches_won', models.PositiveIntegerField(default=0)),
                ('matches_lost', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('games_lost', models.PositiveIntegerField(default=0)),
                ('archived_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='scheduling.archivedseason')),
            ],
            options={
                'ordering': ['team_name'],
            },
        ),
    ]
