# Generated by Django 6.0.5 on 2026-05-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_archivedseason_archivedplayer_archivedteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_team_name', models.CharField(max_length=255)),
                ('away_team_name', models.CharField(max_length=255)),
                ('home_team_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_team_score', models.PositiveIntegerField(blank=True, null=True)),
                ('archived_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='scheduling.archivedseason')),
            ],
            options={
                'ordering': ['date', 'home_team_name'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedPlayerMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('runouts', models.PositiveIntegerField(default=0)),
                ('eight_on_the_breaks', models.PositiveIntegerField(default=0)),
                ('won_all_games', models.BooleanField(default=False)),
                ('archived_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_results', to='scheduling.archivedmatch')),
            ],
            options={
                'ordering': ['team_name', 'player_name'],
            },
        ),
    ]
