# Generated by Django 6.0.3 on 2026-03-13 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_venue_name_venue_unique_venue_name_per_league'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueAdminAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_users', to='core.league')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league_admin_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
