# Generated by Django 6.0.3 on 2026-03-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leagueadminaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='wide_logo_url',
            field=models.URLField(blank=True),
        ),
    ]
