# Generated by Django 6.0.3 on 2026-03-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_league_wide_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='seed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('seed__isnull', False)), fields=('league', 'seed'), name='unique_team_seed_per_league'),
        ),
    ]
