# Generated by Django 6.0.3 on 2026-03-17 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_team_seed_team_unique_team_seed_per_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_rank',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
