# Generated by Django 6.0.3 on 2026-03-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_team_team_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='fee_per_player',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Amount charged per player.', max_digits=6),
        ),
        migrations.AddField(
            model_name='league',
            name='greens_fee',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Portion of fee_per_player paid to the venue.', max_digits=6),
        ),
        migrations.AddField(
            model_name='league',
            name='signup_fee',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Signup fee charged per team.', max_digits=6),
        ),
        migrations.AddField(
            model_name='league',
            name='tournament_target',
            field=models.DecimalField(decimal_places=2, default=90, help_text='Target amount per team added to the end-of-season tournament.', max_digits=8),
        ),
    ]
