# Generated by Django 6.0.5 on 2026-06-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_failedlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='operator_pay_per_player',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid to the league operator per player.', max_digits=6),
        ),
    ]
