# Generated by Django 6.0.5 on 2026-06-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_league_operator_pay_per_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='tournament_target',
            field=models.DecimalField(decimal_places=2, default=300, help_text='Target amount added to the end-of-season tournament.', max_digits=8),
        ),
    ]
