# Generated by Django 5.2.8 on 2026-07-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_league_tournament_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="allow_game_winner_clear",
            field=models.BooleanField(
                default=False,
                help_text="When on, tapping the already-selected game winner in the scoring app deselects it and clears that game result.",
            ),
        ),
    ]
