# Generated by Django 5.2.8 on 2026-07-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_enable_winner_clear_for_emc"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="show_current_score",
            field=models.BooleanField(
                default=False,
                help_text="When on, the scoring app shows the running match score (games won by each side) while games are being entered.",
            ),
        ),
    ]
