# Generated by Django 5.2.8 on 2026-07-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_enable_current_score_for_emc"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="show_breaks",
            field=models.BooleanField(
                default=False,
                help_text='When on, the scoring app marks whose break each game is (home breaks odd rounds, away even rounds; the final round of an odd roster splits by position) and only allows "8 on the break" for the breaking side.',
            ),
        ),
    ]
