# Generated by Django 5.2.8 on 2026-07-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_enable_breaks_for_emc"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="dual_entry_scoring",
            field=models.BooleanField(
                default=False,
                help_text="When on, each captain records their own copy of a match; the app compares them and auto-finalizes when they agree, or shows the differing games/stats for the captains to reconcile.",
            ),
        ),
    ]
