# Generated by Django 5.2.8 on 2026-08-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_enable_dual_entry_go_live"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="allow_admin_score_upcoming",
            field=models.BooleanField(
                default=False,
                help_text="When on, admins can enter scores for upcoming (future-dated) matches in the scoring app, not just matches on or before today.",
            ),
        ),
    ]
