# Generated by Django 6.0.6 on 2026-06-12 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_side', models.CharField(choices=[('W', 'Winner'), ('L', 'Loser'), ('F', 'Grand Final'), ('R', 'Grand Final Reset')], max_length=1)),
                ('round_number', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('complete', 'Complete'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('is_bye', models.BooleanField(default=False)),
                ('winner_next_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('loser_next_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('loser_next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser_sources', to='tournaments.bracketmatch')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.tournamentteam')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.tournamentteam')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_matches', to='tournaments.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.tournamentteam')),
                ('winner_next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_sources', to='tournaments.bracketmatch')),
            ],
            options={
                'ordering': ['bracket_side', 'round_number', 'position'],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'bracket_side', 'round_number', 'position'), name='unique_bracket_match_slot')],
            },
        ),
    ]
