# Generated by Django 6.0.6 on 2026-06-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_bracketmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
