# Generated by Django 5.2.8 on 2026-06-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_tournament_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentplayer",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
