"""
Django settings for leagues project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-only-key')
DEBUG = os.environ.get('DEBUG', 'false').lower() == 'true'

_default_hosts = "emcfunleague.com,www.emcfunleague.com,coed.emcfunleague.com,bogies.emcfunleague.com,localhost,127.0.0.1"
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', _default_hosts).split(',')


# Application definition

INSTALLED_APPS = [
    'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'content',
    'scheduling',
    'results',
    'tournaments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'leagues.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'leagues.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

PRODUCTION_DB_PATH = Path('/var/www/emcfunleague.com/source/db.sqlite3')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': PRODUCTION_DB_PATH if PRODUCTION_DB_PATH.exists() else BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FRONTEND_LEAGUE_ID = int(os.environ.get('FRONTEND_LEAGUE_ID') or 1)

# Maps incoming Host header → league ID so a single process can serve all leagues.
# Override individual entries via env vars (e.g. EMC_HOST=emcfunleague.com).
# FRONTEND_LEAGUE_ID is still used as the fallback when no host matches.
LEAGUE_HOSTS = {
    os.environ.get('EMC_HOST', 'emcfunleague.com'): 1,
    os.environ.get('EMC_WWW_HOST', 'www.emcfunleague.com'): 1,
    os.environ.get('COED_HOST', 'coed.emcfunleague.com'): 2,
    os.environ.get('BOGIES_HOST', 'bogies.emcfunleague.com'): 3,
}

ONTHEHILL_BASE_URL = os.environ.get('ONTHEHILL_BASE_URL', 'http://127.0.0.1:8000')
ONTHEHILL_USERNAME = os.environ.get('ONTHEHILL_USERNAME', '')
ONTHEHILL_PASSWORD = os.environ.get('ONTHEHILL_PASSWORD', '')

# HTTPS / security settings (nginx terminates SSL and forwards via X-Forwarded-Proto)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600  # 1 hour — increase to 31536000 once confirmed working
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    CSRF_TRUSTED_ORIGINS = [
        'https://emcfunleague.com',
        'https://www.emcfunleague.com',
        'https://coed.emcfunleague.com',
        'https://bogies.emcfunleague.com',
    ]
