# Generated by Django 5.2.8 on 2026-07-20 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_league_tournament_target"),
        ("scheduling", "0008_archivedmatch_archivedplayermatchresult"),
        ("scoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                ("home_position", models.PositiveSmallIntegerField()),
                (
                    "winner",
                    models.CharField(
                        choices=[("home", "Home"), ("away", "Away")], max_length=4
                    ),
                ),
                ("runout", models.BooleanField(default=False)),
                ("eight_on_break", models.BooleanField(default=False)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_games",
                        to="scheduling.match",
                    ),
                ),
            ],
            options={
                "ordering": ["round_number", "home_position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "round_number", "home_position"),
                        name="unique_game_per_match_round_position",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LineupSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_lineup_slots",
                        to="scheduling.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_lineup_slots",
                        to="core.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_lineup_slots",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "ordering": ["team_id", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "team", "position"),
                        name="unique_lineup_position_per_match_team",
                    ),
                    models.UniqueConstraint(
                        fields=("match", "team", "player"),
                        name="unique_lineup_player_per_match_team",
                    ),
                ],
            },
        ),
    ]
