# Generated by Django 5.2.8 on 2026-07-29 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_league_dual_entry_scoring"),
        ("scheduling", "0008_archivedmatch_archivedplayermatchresult"),
        ("scoring", "0002_gameresult_lineupslot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("home", "Home"), ("away", "Away")], max_length=4
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_entries",
                        to="scheduling.match",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchEntryGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                ("home_position", models.PositiveSmallIntegerField()),
                (
                    "winner",
                    models.CharField(
                        choices=[("home", "Home"), ("away", "Away")], max_length=4
                    ),
                ),
                ("runout", models.BooleanField(default=False)),
                ("eight_on_break", models.BooleanField(default=False)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="scoring.matchentry",
                    ),
                ),
            ],
            options={
                "ordering": ["round_number", "home_position"],
            },
        ),
        migrations.CreateModel(
            name="MatchEntryLineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineup",
                        to="scoring.matchentry",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.team"
                    ),
                ),
            ],
            options={
                "ordering": ["team_id", "position"],
            },
        ),
        migrations.AddConstraint(
            model_name="matchentry",
            constraint=models.UniqueConstraint(
                fields=("match", "side"), name="unique_entry_per_match_side"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchentrygame",
            constraint=models.UniqueConstraint(
                fields=("entry", "round_number", "home_position"),
                name="unique_entry_game_per_round_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchentrylineup",
            constraint=models.UniqueConstraint(
                fields=("entry", "team", "position"),
                name="unique_entry_lineup_per_team_position",
            ),
        ),
    ]
