# Generated by Django 5.2.8 on 2026-07-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0003_matchentry_matchentrygame_matchentrylineup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("finalized", "Finalized"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
