# Generated by Django 6.0.3 on 2026-03-14 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0005_team_seed_team_unique_team_seed_per_league'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rule_type', models.CharField(choices=[('major_heading', 'Major Heading'), ('minor_heading', 'Minor Heading'), ('rule_entry', 'Rule Entry')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.league')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Added'), ('edited', 'Edited'), ('deleted', 'Deleted')], max_length=10)),
                ('rule_order', models.PositiveIntegerField(blank=True, null=True)),
                ('rule_type', models.CharField(blank=True, max_length=20)),
                ('text', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_audit_logs', to='core.league')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='content.rule')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.UniqueConstraint(fields=('league', 'order'), name='unique_rule_order_per_league'),
        ),
    ]
